# Generated by Django 5.1.2 on 2024-11-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_biowaste', models.PositiveIntegerField(default=0)),
                ('total_glass', models.PositiveIntegerField(default=0)),
                ('total_plastic', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_biowaste', models.PositiveIntegerField()),
                ('max_glass', models.PositiveIntegerField()),
                ('max_plastic', models.PositiveIntegerField()),
                ('current_biowaste', models.PositiveIntegerField(default=0)),
                ('current_glass', models.PositiveIntegerField(default=0)),
                ('current_plastic', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('biowaste', 'Биоотходы'), ('glass', 'Стекло'), ('plastic', 'Пластик')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.storage')),
            ],
        ),
    ]
