# Generated by Django 5.1.2 on 2024-11-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_biowaste',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_glass',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_plastic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Waste',
        ),
    ]
