# Generated by Django 5.1.2 on 2024-11-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organization_max_biowaste_organization_max_glass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='max_biowaste',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storage',
            name='max_glass',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storage',
            name='max_plastic',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
